### ISSUE TITLE
Biathlon - provide description in English

### ISSUE THREAD

**Issue by mpostol** [mpostol/TP#13]
This project is documented using English so any text should be provided in this language.

**Comment by wiktorwandachowicz** [comment]
Biathlon is written in Polish, since it was presented during labs with Polish students.
This involves names of classes, methods, parameters, strings displayed on console, and only then MarkDown descriptions.

So essentially what you ask for is to translate the whole program and description to English.
Should I really do that?

**Comment by mpostol** [comment]
The most important thing is that it is open source project in the public domain. It is true that by the way we are using it also as an illustration for students labs but the same is with many other projects available in public domain. I don't know any one, which is not described in English. 

**I assumed that English is the working language for our students**, because the same is with me.   We are not native speakers but it seems to me that `braking barrier" goal has higher priority then text correctness for the education process.

**I will appreciate any students opinion in this place** - so I have decorated the project by the `help wanted` label.

Because I am spreading the requirements that all contributions must be in the English like language we should prepare a short article on how to contribute.

So far everything is in English - my recommendation is that everything should be kept in English. I hope translation is not big deal for you.

**Comment by wiktorwandachowicz** [comment]
Translation work is already under way. MetricsLib and MetricsLibTests are already finished.

My intention is to create a separate directory `Biathlon-EN` (for English version) apart from existing `Biathlon` (Polish version). This way both audiences will find what they are looking for, in their respective language.
Alternatively I can create branches for these projects, but I'm not completely convinced about that.

**Comment by wiktorwandachowicz** [comment]
Project has been completely translated, and I will soon push it to repository.

Also you wrote (emphasis added):
> We are not native speakers but it seems to me that `braking barrier" goal has **higher priority** then text **correctness for the education process**.

No. I disagree with that. Even if you and me prefer to program in clean English, students should understand the subject well, and adding language barriers is not really necessary.

Even though in "Internet Time" most programmers use English (thus encouraging collaboration), easier understanding for students is preferable in my opinion.

**Comment by wiktorwandachowicz** [comment]
`Biathlon-EN` project has been uploaded. Closing this issue.

**Comment by wiktorwandachowicz** [comment]
`Biathlon-EN` project has been uploaded. Closing this issue.
