### ISSUE TITLE
Add example .dll for Reflection 

### ISSUE THREAD

**Issue by DexterIV** [mpostol/TP#138]
# Adaptive Programming (AP) - Feature Request

## Scope

- [x] add example .dll file with metadata
- [x] add unit tests

## Description 

**Is your feature request related to a problem? Please describe.**
There are no example .dll files. Adding one can help students with reflection topic.

**Describe the solution you'd like**
Example .dll file filled with metadata and covered by unit tests.

**Comment by DexterIV** [comment]
Me (Krzysztof Barden 210139) and Przemysław Fortuna 210176 ( https://github.com/PrzemekFortuna ) want to do this feature.

**Comment by mpostol** [comment]
OK, I will provide advice about where it should be located in the code.

**Comment by mpostol** [comment]
It seems that the best starting point is `ApplicationArchitecture`.  Expand this code. I will appreciate any idea how to distribute this  .dll to be used by others for UT of the reflection functionality.  In the solution, there is also the reflection functionality so let's use it for testing purpose of it if possible.

**Comment by mpostol** [comment]
@DexterIV provide a rough schedule for your work, please. We need it to harmonize the rest of the teamwork.

**Comment by DexterIV** [comment]
We will try for the next week (29.11)
