### ISSUE TITLE
Add serialization example

### ISSUE THREAD

**Issue by mpostol** [mpostol/TP#20]
The following topics are to be ilustrated:
- static class and static elements 
- object state
- singleton
- state machine
- serialization
  - manual serialization
  - reflection based serialization

**Comment by mpostol** [comment]
@wiktorwandachowicz review it please and close if it works for you.

**Comment by mpostol** [comment]
Closed by mistake.

**Comment by wiktorwandachowicz** [comment]
XML example compiles and works. I can open resulting  **bin/Debug/CustomData/Catalog.xml** file in MSIE or Firefox, and these two perform XML to HTML XSL transformation using **catalog.xslt** file.
This doesn't work with Google Chrome, though. I have no idea why.

However, there is a typo in code:

`IStylesheetNameProvider.StylesheetNmane`

I think the property should be called "Stylesheet**Name**".

**Comment by mpostol** [comment]
@wiktorwandachowicz  I propose:
1. fix the typo and commit
2. Define new issue for the Google Chrome
3. Close this issue.

**Comment by mpostol** [comment]
In repo the the typo has been already fixed. 
I have reported new issue related to Google Chrome.
