### ISSUE TITLE
Add LINQ examples

### ISSUE THREAD

**Issue by wiktorwandachowicz** [mpostol/TP#21]

**Comment by wiktorwandachowicz** [comment]
Example is complete, with unit tests, documentation, etc.
Closing the issue.

**Comment by mpostol** [comment]
Let me review it firest.

**Comment by wiktorwandachowicz** [comment]
Modified LINQ examples, next step is to switch back to MSTest instead of NUnit.

**Comment by mpostol** [comment]
It works for me.
