### ISSUE TITLE
TPA - add Attributes example.

### ISSUE THREAD

**Issue by mpostol** [mpostol/TP#31]

**Comment by Drutol** [comment]
I'd be interested in creating such example. Are there key points that are required or just general use cases and examples?

**Comment by mpostol** [comment]
OK The key points are as follows:

1. Derive from System.ComponentModel.DescriptionAttribute
2. The description defined is only a key.
3. The description should be returned in the language setup by the underlying operating system or default.

Scope:
1. Add UT testing the usage. The class must be used in UT Project, i.e. added as the attribute to private testing class. 
2. Using dependency injection or moc/fixture replace the call to OS.

This scope may be forked to two PR each for 5 points.
 
The task must be accomplished up too Sunday, because I need this for next lecture.

Go ahead and good luck.

**Comment by Drutol** [comment]
So if I understand correctly string given in attribute's `Description` property should define key for localized string which will be then replaced by one provided by mocked OS call.

**Comment by mpostol** [comment]
Precisely speaking:
... will be then replaced by one provided by application resources (a satellite assemblies) according to language setup by the operating system. See more:
 
[Localization](https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/localization)

For testing we must replace the call to operating system recovering current language.
Today I will define the class and UT project to be used as the placeholder for further development.

**Comment by Drutol** [comment]
Okay I think we are on the same page now, thanks for clarification.

**Comment by mpostol** [comment]
Leave a comment

**Comment by Drutol** [comment]
As in I should leave a comment? If so my comment has been submitted in pull request issue #33. I was hoping GitHub would reference this request here but it seems to be working only for repo owners and collaborators.
