### ISSUE TITLE
TPA Add example for Asynchronous Programming in the .NET Framework

### ISSUE THREAD

**Issue by mpostol** [mpostol/TP#35]
TPA Add example for Asynchronous Programming in the .NET Framework

Scope:

1. *[Thread](https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread?view=netframework-4.7)* and *[Thread​Pool Class](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadpool?view=netframework-4.7)*.
	* Synchronization
	* Critical section
	* Real time programming  *[Timer Class](https://docs.microsoft.com/en-us/dotnet/api/system.threading.timer?view=netframework-4.7)*
1. [Asynchronous Programming Patterns](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/):
	* Asynchronous Programming Model (APM)
	* Event-based Asynchronous Pattern (EAP)
	* [Task Parallel Library (TPL)](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-parallel-library-tpl)

**Comment by pmysl** [comment]
I would like to do this example

**Comment by mpostol** [comment]
Great, I appreciate. Are you sure you could managed to cover all topics. My concern is that it is scheduled for the next week. I am thinking about splitting this issue to two. Is there someone interested to contribute. 

Anyway I will prepare placeholders for further development very soon.

Good luck.

**Comment by mpostol** [comment]
Merged PR at 0c45986d60872b2bd1352e90f601185d78c5ce36
Th code must be reviewed.

**Comment by mpostol** [comment]
### `TPA.AsynchronousBehavior.Threading.ThreadsExample` issues

* Critical section must be extracted from `ThreadsExample` to a separate classs, because usually working processes are not started inside.
* Instead of of using `IsConsistent` an exception should be thrown

I will take over these issues.

**Comment by mpostol** [comment]
We need the deadlock example.

### Race Conditions and Deadlocks

The .NET library provides sufficient thread support that you will rarely find yourself: creating your own threads and managing synchronization manually. 

Thread synchronization can be tricky, especially in complex programs. If you do decide to create your own threads, you must confront and solve all the traditional problems of thread synchronization, such as race conditions and deadlock.

**Comment by mpostol** [comment]
Name of class  must be rename. 
Instead of keyboard a generic produced must be implemented.

**Comment by mpostol** [comment]
Combine the projects into one.

**Comment by mpostol** [comment]
Error in EAPReadKeyFromKeyboardBufferAsyncTest the loop limit is wrong.
