### ISSUE TITLE
TPA - Reflection method and property get/set call example

### ISSUE THREAD

**Issue by mpostol** [mpostol/TP#48]
TPA - Reflection method and property get/set call example

Starting point:

* [PropertyInfo Class](https://msdn.microsoft.com/en-us/library/system.reflection.propertyinfo.aspx)
* [MethodInfo Class](https://msdn.microsoft.com/en-us/library/system.reflection.methodinfo.aspx)

**Comment by Lunada** [comment]
Hello, I am interested into solving this topic.

**Comment by mpostol** [comment]
Great, go ahead. Good luck. Let me know your deadline target.

**Comment by Lunada** [comment]
If this thing is need to be done on this wednesday I will set DL on tommorow. If there is no need to rush I can make it on next sunday.

**Comment by mpostol** [comment]
I don't need it this week.

**Comment by Anakinud** [comment]
I'm interested in this topic, can I try to solve this?

**Comment by mpostol** [comment]
Sure go ahead - I have no feedback from @Lunada so we can consider it not assigned.

BTW the commit 
https://github.com/mpostol/TP/commit/e25c7e442b037fd28add33817f5850dfe700c345 
Does it look like a mistake?
Any idea where to locate the example?

**Comment by Anakinud** [comment]
I would like to ask for opinion, because Properties are practically two methods and the field. So, I assumed that I can use `MethodMetadata`. However, all information about this object is private, I can get all this information, but it would be easier if we make them public. I have to options:

1. Reflect everything from `PropertyInfo`.
2. Make `internal`/`public` fields/properties from `MethodMetadata`

Which of these two approaches you see more preferable?

**Comment by mpostol** [comment]
@Anakinud  Now I have got it and you should forget about `MethodMetadata`. Using reflection for modeling is the next lesson.  The example must be very short and useful. 
Recall our discussion about what is `Binding`. In case you are not sure just use F12 :) using snipped below.

# Goal

Demonstrate how this works.

```xml
      <TextBox Text="{Binding CurrentUser.Name}" Grid.Column="0" Grid.Row="0" />
```
# Scope
- forget about xaml 
- create something like`Binding` 
- crete *data source* implementing `INotifyPropertyChange`
- create *data consumer* exposing propert something like `Text`
- Use your `Binding` to couple *data source* and *data consumer* using reflecion
- change the *data source* and test if the modification is propagated to *data consumer*

# Challenge
Partially the scope must be implemented in Unit Test.  Recall our discussion about DI - there must be no doubts where parts of the code must be located !! 

* Good luck :)

**Comment by mpostol** [comment]
@Anakinud let me know how it works for you.

**Comment by Anakinud** [comment]
Ok, I see, i missunderstood the topic, I thought is about creating PropertyMetadata, but now I see.

**Comment by mpostol** [comment]
@Anakinud any plans? Please commit to your fork referencing this issue to allow me to see the progress.  
FYI: I am going to close this milestone very soon. So this task will be moved to the backlog. I am not going to touch the TPA folder in a next few weeks so you can work on your own pace  :relaxed: without the necessity to synchronize the fork with the origin. 
:+1:

**Comment by Anakinud** [comment]
@mpostol I'm during research phase let say. I even dug to binding source code, but there isn't used reflection so I'm going to create how I see it.

**Comment by Anakinud** [comment]
I just added draw of DataBinding, currently working on tests.

**Comment by Anakinud** [comment]
I'm not making pull request. I'm open to any comments.

**Comment by mpostol** [comment]
@Anakinud  is exactly what I am looking for. Good job :+1: 
I am only going to change the formatting to meet the origin but don't bother about it.
Go ahead and PR.

**Comment by Anakinud** [comment]
So I think issue can be closed

**Comment by mpostol** [comment]
I need to finally review the code after the merge. To allow you to review final code after modifications if required I will assign it to you again so you will have the chance to close it. Give me a couple of days - I am very busy with three other challenging projects.

**Comment by mpostol** [comment]
@Anakinud  I cannot assign it to you. So I am closing and if there is something more to add reopen it please and comment.

Thanks for cooperation - good job :ok_hand: .

**Comment by mpostol** [comment]
dataSource == null exception must be thrown and the test must be added.
