### ISSUE TITLE
TPA Using Dynamic Objects Example

### ISSUE THREAD

**Issue by mpostol** [mpostol/TP#50]
### Starting point

[Walkthrough: Creating and Using Dynamic Objects ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/walkthrough-creating-and-using-dynamic-objects)

### Scope

* added and implement method derived for DynamicObject allowing to use property name as a string to search a text file.
* add UT
* add text file

**Comment by AyronKotlet** [comment]
Hello, I'll prepare this example. Should it be ready till the next lecture?

**Comment by mpostol** [comment]
Go ahead, I don't need it right now. You have 2-3 weeks to accomplish this task. 
Good luck.

**Comment by mpostol** [comment]
:+1: but must be reviewed :smile: 
Review the file `TPA/Reflection/DynamicType/ReadOnlyFile.cs` to make sure it fits the lecture requirements.
