### ISSUE TITLE
TPA - Example of the Monitor class

### ISSUE THREAD

**Issue by mpostol** [mpostol/TP#58]
Starting Point:
[Overview of Synchronization Primitives](https://docs.microsoft.com/en-us/dotnet/standard/threading/overview-of-synchronization-primitives)

**Comment by 210342** [comment]
I would like to prepare an example for this issue

**Comment by mpostol** [comment]
OK, go ahead. I will provide you more info on very soon.

**Comment by mpostol** [comment]
I have closed it by mistake.

**Comment by mpostol** [comment]
Review the code. It looks like finished.

**Comment by mpostol** [comment]
This issue must be reviewed and code transferred to Concurrent Programming

**Comment by mpostol** [comment]
The code will be continued as the #218 issue
