### ISSUE TITLE
TPA - Plug-In simple example

### ISSUE THREAD

**Issue by mpostol** [mpostol/TP#61]
### Starting point:
https://msdn.microsoft.com/en-us/library/ms972962.aspx

### Scope:

* Simple example of use plug-ins
* Add Unit Tests

Your code add to the Composition project.

**Comment by mpostol** [comment]
Consider using [Add-ins and Extensibility](https://docs.microsoft.com/en-us/dotnet/framework/add-ins/index)

**Comment by MJayJ** [comment]
I would like to add this example.

**Comment by mpostol** [comment]
OK take it over.

**Comment by mpostol** [comment]
It is done.  Good job.
